---
services:
  traefik-consul-registrator:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      # Timezone setting
      TZ: Europe/Paris
      # Command line options as environment variables
      TCR_CONSUL_API: ${TCR_CONSUL_API}
      TCR_SYNC_INTERVAL: "30"
      TCR_INTERNAL: "false"
      TCR_CLEANUP: "true"
      TCR_TAGS: "traefik,service"
      # other options
      # TCR_DEREGISTER: "always"
      # TCR_NETWORKS_PRIORITY: "bridge,traefik"
      # TCR_HOST_IP: ""